### ISSUE TITLE
 Unavailable spell used in oUF_GCD for rogues

### ISSUE THREAD

**Issue by abdes** [SanUI/SanUI#10]
In `oUF_GCD.lua`, Sap is not available at early levels, causing errors when levelling a new rogue. `Sinister Strike` is and triggers the GCD:

```
	1752,			-- Sinister Strike (Rogue)
```

**Comment by SanUI** [comment]
Thanks, fixed in https://github.com/SanUI/SanUI/commit/c3ccface058a4d0d2a31c4dd6e7103f4fdb5d325
