### ISSUE TITLE
Raid utilities buttons do not work if ActionButtonUseKeyDown is enabled

### ISSUE THREAD

**Issue by abdes** [SanUI/SanUI#11]
## Problem 

`ActionButtonUseKeyDown` can be set to `1` to have action bar buttons fire on key-press not on key-release, which is a valid option for people who wanna play according to that style.

Raid utilities button stop working if such CVar is set to 1. 

## Suggested Solution

The reason is that when the button are created as SecureButtontemplate instances, they are not specifically listening for specific mouse click events.

This is done through [Button:RegisterForClicks()](https://wowpedia.fandom.com/wiki/API_Button_RegisterForClicks), which tells the button what clicks to look for (Left, Right, Middle, etc.) If you don't register any, it won't work when `ActionButtonUseKeyDown` is set to `1`.

This is a separate function from just telling a frame it should react to mouse events.

**Comment by SanUI** [comment]
Thanks for both the report and the investigation! Fixed in https://github.com/SanUI/SanUI/commit/e1f9814aa54eb2dac19a88c100d43ad166b68714
