### ISSUE TITLE
Only customize Tukui stance bar if it exists

### ISSUE THREAD

**Issue by abdes** [SanUI/SanUI#12]
In:
https://github.com/SanUI/SanUI/blob/48dc49fc013b9e67ab0ac9c79a5e1e8eb28a3b6c/SanUI/Modules/AddonMods/tukui.lua#L151

An error occurs if Tukui stance bar is disabled in Tukui config.

**Comment by SanUI** [comment]
Fixed in https://github.com/SanUI/SanUI/commit/12329201cea8f0173cd8f53f462b6e1243548154, thank you!
