### ISSUE TITLE
cooline issue

### ISSUE THREAD

**Issue by Urguk** [SanUI/SanUI#3]
Anyway to get cooline to show up if bar 3 is disable would like to go access bar 1 and bar 2.

**Comment by SanUI** [comment]
Generally this isn't supported. But you could try to delete [those lines](https://github.com/SanUI/SanUI/blob/master/SanUI/Modules/AddonMods/coolline.lua#L31-L44), which should make cooline show up.

**Comment by Urguk** [comment]
Ty for he information

**Comment by Urguk** [comment]
this  the  error message when I disable bar 3 in Tukui. 


Message: Interface\AddOns\SanUI\Modules\AddonMods\tukui.lua:94: attempt to index local 'TukuiBar3' (a nil value)
Time: Tue May  3 20:47:20 2022
Count: 1
Stack: Interface\AddOns\SanUI\Modules\AddonMods\tukui.lua:94: attempt to index local 'TukuiBar3' (a nil value)
[string "@Interface\AddOns\SanUI\Modules\AddonMods\tukui.lua"]:94: in function <Interface\AddOns\SanUI\Modules\AddonMods\tukui.lua:31>
[string "=[C]"]: ?
[string "=[C]"]: in function `Enable'
[string "@Interface\AddOns\Tukui\Core\Loading.lua"]:244: in function <Interface\AddOns\Tukui\Core\Loading.lua:226>

Locals: TukuiBar1 = TukuiActionBar1 {
 0 = <userdata>
 GetBar = <function> defined @Interface\AddOns\Tukui\Modules\ActionBars\Bar1.lua:48
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 Button3 = ActionButton3 {
 }
 Button5 = ActionButton5 {
 }
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:793
 Button10 = ActionButton10 {
 }
 Button4 = ActionButton4 {
 }
 Button2 = ActionButton2 {
 }
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 Button1 = ActionButton1 {
 }
 Button12 = ActionButton12 {
 }
 Page = <table> {
 }
 MoverName = "Action Bar #1"
 Button6 = ActionButton6 {
 }
 Button11 = ActionButton11 {
 }
 Button8 = ActionButton8 {
 }
 Shadow = <unnamed> {
 }
 Button7 = ActionButton7 {
 }
 Button9 = ActionButton9 {
 }
 Backdrop = <unnamed> {
 }
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
}
TukuiBar2 = TukuiActionBar2 {
 0 = <userdata>
 Shadow = <unnamed> {
 }
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 Button3 = MultiBarBottomLeftButton3 {
 }
 Button5 = MultiBarBottomLeftButton5 {
 }
 Button6 = MultiBarBottomLeftButton6 {
 }
 Button10 = MultiBarBottomLeftButton10 {
 }
 Button4 = MultiBarBottomLeftButton4 {
 }
 Button2 = MultiBarBottomLeftButton2 {
 }
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 Button1 = MultiBarBottomLeftButton1 {
 }
 Button12 = MultiBarBottomLeftButton12 {
 }
 Backdrop = <unnamed> {
 }
 MoverName = "Action Bar #2"
 Button11 = MultiBarBottomLeftButton11 {
 }
 Button8 = MultiBarBottomLeftButton8 {
 }
 Button7 = MultiBarBottomLeftButton7 {
 }
 Button9 = MultiBarBottomLeftButton9 {
 }
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:793
}
TukuiBar3 = nil
TukuiBar4 = nil
TukuiBar5 = nil
PetBar = TukuiPetActionBar {
 0 = <userdata>
 Shadow = <unnamed> {
 }
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 Button3 = PetActionButton3 {
 }
 Button5 = PetActionButton5 {
 }
 Button6 = PetActionButton6 {
 }
 Button10 = PetActionButton10 {
 }
 Button4 = PetActionButton4 {
 }
 Button2 = PetActionButton2 {
 }
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 Button1 = PetActionButton1 {
 }
 Backdrop = <unnamed> {
 }
 MoverName = "Pet Action Bar"
 Button8 = PetActionButton8 {
 }
 Button7 = PetActionButton7 {
 }
 Button9 = PetActionButton9 {
 }
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:793
}
Size = 32
Spacing = 4
(*temporary) = <function> defined @Interface\AddOns\Tukui\Core\Toolkit.lua:51
(*temporary) = TukuiActionBar2 {
 0 = <userdata>
 Shadow = <unnamed> {
 }
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 Button3 = MultiBarBottomLeftButton3 {
 }
 Button5 = MultiBarBottomLeftButton5 {
 }
 Button6 = MultiBarBottomLeftButton6 {
 }
 Button10 = MultiBarBottomLeftButton10 {
 }
 Button4 = MultiBarBottomLeftButton4 {
 }
 Button2 = MultiBarBottomLeftButton2 {
 }
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 Button1 = MultiBarBottomLeftButton1 {
 }
 Button12 = MultiBarBottomLeftButton12 {
 }
 Backdrop = <unnamed> {
 }
 MoverName = "Action Bar #2"
 Button11 = MultiBarBottomLeftButton11 {

**Comment by SanUI** [comment]
Yeah SanUI isn't really prepared for this kind of stuff..

Try changing [this line](https://github.com/SanUI/SanUI/blob/master/SanUI/Modules/AddonMods/tukui.lua#L94) to

```lua
if TukuiBar3 and TukuiBar3.Backdrop then
```
