### ISSUE TITLE
oUF_GCD uses warrior spell that is not available

### ISSUE THREAD

**Issue by abdes** [SanUI/SanUI#4]
https://github.com/SanUI/SanUI/blob/35e3d320d377613dccb03b9f51c4010b21a3aa8f/oUF_GCD/oUF_GCD.lua#L26

Maybe use something like 'Slam'?

**Comment by SanUI** [comment]
Hey thanks for notifyin me, I don't play a warrior, so I wouldn't notice. Does every warrior have `Slam`? If not, do you know any spell that every warrior has? Thanks!

**Comment by abdes** [comment]
> Hey thanks for notifying me, I don't play a warrior, so I wouldn't notice. Does every warrior have `Slam`? If not, do you know any spell that every warrior has? Thanks!

Yes, I checked Slam is in every spec and is among the first spells to learn. I actually made the change myself and it works.

**Comment by SanUI** [comment]
Awesome, fix coming, thanks!
