### ISSUE TITLE
How to use OmniCD with party frames in SanUI

### ISSUE THREAD

**Issue by abdes** [SanUI/SanUI#5]
I could not find any way to do that. Is SanUI using party frames from any of the supporting addons by OmniCD?

If not, can you explain how to disable SanUI party frames (for groups up to 5)  to use an alternate one?

**Comment by SanUI** [comment]
I'm not fully understanding the question. SanUI ships tullaCC, which should play the same role as OmniCD afaik. The icons in the party frames should have sweep animations (I do have some disabled for druid hots, though). Most don't show numbers for size reasons...

Maybe take a step back and tell me what you'd want to achieve?

**Comment by abdes** [comment]
I'd like to display the party important CDs on the side of the party frames, like what OmniCD does. The image below shows an example of that.

https://i.imgur.com/zhGuSJN.png

Each party member can have selected CDs (of that party member) shown near its unit frame. This is extremely useful in M+.

How can we achieve the same with tullaCC?

_PS: I actually love your UI and the work you did. It's just the party unit frames that bothers me too much for M+ runs. I need the CDs and I would love to be able to make the frames bigger and move them closer to my center view, even when I'm playing as DPS, as often I lead M+ runs._

**Comment by SanUI** [comment]
Oh, ok, yeah, no, that can't be done with tullaCC.

To disable the raid- and partyframes (they're the same), you need to remove the following lines:

https://github.com/SanUI/SanUI/blob/master/SanUI/SanUI.toc#L23
https://github.com/SanUI/SanUI/blob/master/SanUI/Modules/AddonMods/blizzard.lua#L19-L23

At least, I hope, I did not test extensively :)

**Comment by abdes** [comment]
Thanks. It's a pity we cannot simply disable player and target unit frames in tukui and leave the party/raid :-). I\ll see if I can find a way to make OmniCD recognize your unit frames, otherwise, I'll need to replace them.

**Comment by abdes** [comment]
> To disable the raid- and partyframes (they're the same), you need to remove the following lines:
> 
> https://github.com/SanUI/SanUI/blob/master/SanUI/SanUI.toc#L23 https://github.com/SanUI/SanUI/blob/master/SanUI/Modules/AddonMods/blizzard.lua#L19-L23

I just removed the module from the toc file and left the Blizzard disabling code as is because I'm using vudho for unit frames. Works like a charm for now (although I am missing the auto layout changes you built into your UI, which I will now need to extend to vudho profile changes or make  spec specific profiles in vudho).

Thanks again for the support.
