### ISSUE TITLE
Unavailable spell used in oUF_GCD for mages

### ISSUE THREAD

**Issue by abdes** [SanUI/SanUI#9]
In `oUF_GCD.lua`, Frosfire bolt is not a baseline anymore for mages. Frostbolt is:

```
	116,			-- Frostbolt (Mage)
```

**Comment by SanUI** [comment]
Thanks, fixed in https://github.com/SanUI/SanUI/commit/c3ccface058a4d0d2a31c4dd6e7103f4fdb5d325

**Comment by abdes** [comment]
The spell ID should be 116, the code still has 115.

**Comment by SanUI** [comment]
Fixed on master. Thanks for looking at it :)
